language: node_js
sudo: false
node_js:
  - 6.9.1
  - 14
install:
  - npm install phantomjs-prebuilt@2.1.16 --ignore-scripts
  - npm install karma --save-dev
  - npm install --save-dev webpack
script:
  - npm test
after_success:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
arch:
  - amd64
  - ppc64le
