language: node_js
sudo: false
node_js:
  - 6.9.1
  - 14
install:
  - npm install phantomjs-prebuilt@2.1.16 --ignore-scripts
  - npm install -SD karma-webpack webpack
  - npm install -g karma-jasmine
script:
  - npm test
after_success:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
arch:
  - amd64
  - ppc64le
